# Generated by Django 5.2 on 2025-04-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Correction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_sentence', models.TextField()),
                ('corrected_sentence', models.TextField()),
                ('explanation', models.TextField()),
                ('difficulty', models.CharField(blank=True, max_length=10, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
